[Settings]
  ID = "niceb5y-net"

[build]
  publish = "dist/"
  command = "yarn run build"

[[redirects]]
from = "/"
to = "/index.html"
status = 200
force = false

[[redirects]]
from = "/*"
to = "/_404/index.html"
status = 404
force = false