[Settings]
  ID = "niceb5y-net"

[build]
  publish = "public/"
  command = "yarn run build"

[[redirects]]
from = "/"
to = "/index.html"
status = 200
force = false

[[redirects]]
from = "/*"
to = "/404.html"
status = 404
force = false
